const apis = {
    'urlDataModulair' : "https://api.quant-aq.com/device-api/v1/devices/MOD-PM-00053/data/?sort=timestamp,desc&limit=1",
    'urlInfoModulair' : "https://api.quant-aq.com/device-api/v1/devices/MOD-PM-00053",
    'urlDataModulair2' : "https://api.quant-aq.com/device-api/v1/devices/MOD-PM-00075/data/?sort=timestamp,desc&limit=1",
    'urlInfoModulair2' : "https://api.quant-aq.com/device-api/v1/devices/MOD-PM-00075",
    'urlDataClarity' : "https://clarity-data-api.clarity.io/v1/measurements?code=AN92S2XQ&limit=1",
    'urlInfoClarity' : "https://clarity-data-api.clarity.io/v1/devices?code=AN92S2XQ",
    'urlDataClarity2' : "https://clarity-data-api.clarity.io/v1/measurements?code=A431GG69&limit=1",
    'urlInfoClarity2' : "https://clarity-data-api.clarity.io/v1/devices?code=A431GG69",
    'urlDataNuboair' : "https://cloud.nubo-air.com/api/95b46c99-895c-4959-bae0-e661b4360963/devices/nb1-86xksp-11-38-26/measurements/v2?aggregationTimeRange=None&returnMissing=true",
    'urlInfoNuboair' : "https://cloud.nubo-air.com/api/95b46c99-895c-4959-bae0-e661b4360963/devices",
    'urlInfoEva' : "https://makesens.aws.thinger.io/v1/users/MakeSens/devices/E2_00001",
    'urlDataEva' : "https://makesens.aws.thinger.io/v1/users/MakeSens/buckets/BE2_00001/data?items=1",
    'urlInfoEva2' : "https://makesens.aws.thinger.io/v1/users/MakeSens/devices/E2_00002",
    'urlDataEva2' : "https://makesens.aws.thinger.io/v1/users/MakeSens/buckets/BE2_00002/data?items=1",
    'urlDataPurpleair': "https://www.purpleair.com/json?key=NMXWHM1VZE35VWJM&show=113873",   
    'api_keyModulair' : "Y25LI6BNJQ4YPGGHXM0GT08M",
    'api_keyEva' : "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiJUT0tFTl9TQUxMRSIsInVzciI6Ik1ha2VTZW5zIn0.Qmw4E8_2yqf29nWq9qj5YtcjwT0NpzDYTHdLezq4xPY",
    'api_keyClarity' : "O67ZARLVyFiTnxx3Q8USbpy8iBenoCmD7DsT6oW6",
    'api_keyNuboair' : "d76ljq9Nr9C6PCoAJxZWk2cLSIxCen8AN6v+tDULCKI=",
    'api_keyAirlink': "p2aqlokszlu2yzhw8glo2sb6otgcq4ry",
    'urlTest' : "https://api.quant-aq.com/device-api/v1/devices/MOD-PM-00053/data/",
}

module.exports = apis